# Site settings
title: Littldev
email: support@littlstar.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
baseurl: '' # the subpath of your site, e.g. /blog/
url: 'http://developer.littlstar.com' # the base hostname & protocol for your site

# Social Settings
social:
  github:
    name: littlstar
    url: https://github.com/littlstar
  twitter:
    name: littlstardev
    url: https://twitter.com/littlstardev

# Build settings
markdown: kramdown

kramdown:
  input: GFM

# Google Analytics
ga_tracking_id: UA-43519114-8
